<template>
  <main>
    <section id="1" v-scrollspy="onScrollTo">
      <h1>1</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="a" v-scrollspy="onScrollTo">
      <h1>a</h1>
    </section>

    <section id="b" v-scrollspy="onScrollTo">
      <h1>b</h1>
    </section>

    <section id="2" v-scrollspy="onScrollTo">
      <h1>2</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="3" v-scrollspy="onScrollTo">
      <h1>3</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="4" v-scrollspy="onScrollTo">
      <h1>4</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="5" v-scrollspy="onScrollTo" style="height: 3000px">
      <h1>5</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="6" v-scrollspy="onScrollTo">
      <h1>6</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="7" v-scrollspy="onScrollTo">
      <h1>7</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="8" v-scrollspy="onScrollTo">
      <h1>8</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <section id="9" v-scrollspy="onScrollTo">
      <h1>9</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a ligula arcu. Quisque non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in fermentum ipsum, at porttitor eros. Curabitur placerat id est non eleifend. Morbi at velit porttitor, consequat neque vel, finibus sem. In nec euismod nulla. Vivamus iaculis consequat imperdiet. Nunc tempor ac ex a convallis. Duis ex sem, venenatis et arcu quis, gravida cursus quam. Mauris ac egestas tellus, non sollicitudin lorem. Curabitur eu diam nulla. Cras dignissim tortor sit amet quam sagittis vehicula. Nulla augue ante, dictum ut enim id, ullamcorper lacinia nibh.</p>
    </section>

    <div id="log">{{ active }}</div>
  </main>
</template>

<script>
import scrollspy from '..'

export default {
  directives: { scrollspy },

  data: () => ({
    active: ''
  }),

  methods: {
    onScrollTo(el) {
      this.active = el.id
    }
  }
}
</script>

<style>
#log {
  position: fixed;
  right: 0;
  top: 50px;
  width: 30px;
  height: 30px;
  border: 1px solid red;
  display: flex;
  justify-content: center;
  align-items: center;
}

section {
  border: 1px solid blue;
}
</style>
